/**
 * extract-data.mjs
 * מחלץ DEFAULT_SKILLS ו-PIPELINES מה-HTML המקורי
 * ויוצר קבצי JS נפרדים ב-src/data/
 * אין eval — משתמש ב-dynamic import של קבצים זמניים
 */

import { readFileSync, writeFileSync, mkdirSync, unlinkSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const SRC = join(__dirname, '../backup/claude-skills-guide.html')
const OUT = join(__dirname, '../src/data')
const TMP = join(__dirname, '../src/data/_tmp_extract.mjs')

// קרא את ה-HTML
const html = readFileSync(SRC, 'utf8')

// חלץ את ה-script block
const scriptMatch = html.match(/<script>([\s\S]*?)<\/script>/)
if (!scriptMatch) throw new Error('No script tag found')
const script = scriptMatch[1]

// חלץ array/object literal מה-script לפי שם משתנה
function extractLiteral(src, varName) {
  const startRe = new RegExp(`const ${varName}\\s*=\\s*`)
  const startMatch = src.match(startRe)
  if (!startMatch) throw new Error(`Cannot find ${varName}`)

  const startIdx = src.indexOf(startMatch[0]) + startMatch[0].length
  let depth = 0
  let i = startIdx
  let inString = false
  let stringChar = ''
  let escaped = false

  while (i < src.length) {
    const ch = src[i]
    if (escaped) { escaped = false; i++; continue }
    if (ch === '\\') { escaped = true; i++; continue }
    if (!inString && (ch === '"' || ch === "'" || ch === '`')) {
      inString = true; stringChar = ch; i++; continue
    }
    if (inString && ch === stringChar) { inString = false; i++; continue }
    if (inString) { i++; continue }
    if (ch === '[' || ch === '{') depth++
    if (ch === ']' || ch === '}') { depth--; if (depth === 0) { i++; break } }
    i++
  }

  return src.slice(startIdx, i)
}

console.log('מחלץ DEFAULT_SKILLS...')
const skillsRaw = extractLiteral(script, 'DEFAULT_SKILLS')
console.log(`  אורך: ${skillsRaw.length} תווים`)

console.log('מחלץ PIPELINES...')
const pipelinesRaw = extractLiteral(script, 'PIPELINES')
console.log(`  אורך: ${pipelinesRaw.length} תווים`)

// כתוב קובץ זמני עם export — ואז import אותו
mkdirSync(OUT, { recursive: true })

writeFileSync(TMP, `
export const DEFAULT_SKILLS = ${skillsRaw}
export const PIPELINES = ${pipelinesRaw}
`)

// dynamic import
const { DEFAULT_SKILLS, PIPELINES } = await import(TMP + `?t=${Date.now()}`)

// נקה קובץ זמני
unlinkSync(TMP)

const mcpSkills = DEFAULT_SKILLS.filter(s => s.cat === 'mcp')
const regularSkills = DEFAULT_SKILLS.filter(s => s.cat !== 'mcp')

console.log(`\n  סקילים רגילים: ${regularSkills.length}`)
console.log(`  MCP skills: ${mcpSkills.length}`)
console.log(`  פייפליינים: ${PIPELINES.length}`)

// skills.js
writeFileSync(join(OUT, 'skills.js'),
`// AUTO-GENERATED by extract-data.mjs
// ${regularSkills.length} סקילים (לא MCP)
export const SKILLS = ${JSON.stringify(regularSkills, null, 2)}
`)
console.log('\n✅ src/data/skills.js')

// mcp.js
writeFileSync(join(OUT, 'mcp.js'),
`// AUTO-GENERATED by extract-data.mjs
// ${mcpSkills.length} חיבורי MCP
export const MCP_SKILLS = ${JSON.stringify(mcpSkills, null, 2)}
`)
console.log('✅ src/data/mcp.js')

// pipelines.js — שומר את ה-raw JS כי יש getters
writeFileSync(join(OUT, 'pipelines.js'),
`// AUTO-GENERATED by extract-data.mjs
// ${PIPELINES.length} פייפליינים
export const PIPELINES = ${pipelinesRaw}
`)
console.log('✅ src/data/pipelines.js')

// index.js
writeFileSync(join(OUT, 'index.js'),
`// Data barrel
import { SKILLS } from './skills.js'
import { MCP_SKILLS } from './mcp.js'
import { PIPELINES } from './pipelines.js'
export * from './config.js'
export { PIPELINES }
export const ALL_SKILLS = [...SKILLS, ...MCP_SKILLS]
`)
console.log('✅ src/data/index.js')

console.log(`\n🎉 ${DEFAULT_SKILLS.length} סקילים + ${PIPELINES.length} פייפליינים`)
